### ISSUE TITLE
Hitting the cache all the time

### ISSUE THREAD

**Issue by reduards** [Azure-Samples/AI-Gateway#63]
Hello,

I am hitting the cache in the lab runbook even though i ask a completly different questions about totally different topic.

<img width="784" alt="Screenshot 2024-10-15 174542" src="https://github.com/user-attachments/assets/35de622c-4413-422b-9d26-2d21a6fe7cb2">

As you can see here when i changed the question from asking the time to "what are the best cars" its hitting the cache and returning the answer for the previous prompt about time....

**Comment by Wilsven** [comment]
Have you tried playing around with the `score-threshold`?

**Comment by vieiraae** [comment]
Yes, the score threshold in the sample is very high. If you change to something like 0.05 you will have different results. I will update the sample. Thanks
